### ISSUE TITLE
gzip.cwl error for 'output_filename' key

### ISSUE THREAD

**Issue by kamichiotti** [OpenGenomics/mc3#9]
Command used: `cwltool mc3/utils/gzip.cwl gzip.json`

`gzip.json file:
{
  "dbsnp" : {
    "class" : "File",
    "path" : "/home/exacloud/lustre1/SpellmanLab/chiotti/gdan_pipelines/mc3_dev/dbsnp_132_b37.leftAligned.vcf.gz"
    }
}`

Resultant error:
`/home/users/chiotti/local/bin/cwltool 1.0.20180130110340
Resolved 'mc3/utils/gzip.cwl' to 'file:///home/exacloud/lustre1/SpellmanLab/chiotti/gdan_pipelines/mc3_dev/mc3/utils/gzip.cwl'
Got workflow error
Traceback (most recent call last):
  File "/home/users/chiotti/.local/lib/python2.7/site-packages/cwltool/main.py", line 291, in single_job_executor
    for r in jobiter:
  File "/home/users/chiotti/.local/lib/python2.7/site-packages/cwltool/draft2tool.py", line 434, in job
    raise validate.ValidationException("stdout must be a relative path, got '%s'" % j.stdout)
  File "/home/users/chiotti/.local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 157, in __exit__
    raise self.makeError(six.text_type(exc_value))
ValidationException: mc3/utils/gzip.cwl:5:1: Expression evaluation error:
mc3/utils/gzip.cwl:5:1: inputs does not contain key 'output_filename'
Workflow error, try again with --debug for more information:
mc3/utils/gzip.cwl:5:1: Expression evaluation error:
                        inputs does not contain key 'output_filename'`

**Comment by kamichiotti** [comment]
Changing `stdout` and the output `glob` to `$(inputs.dbsnp.basename)` results in:

```
[job gzip.cwl] /tmp/tmp90O2XU$ gzip \
    -d \
    /tmp/tmpjPJXyE/stge09f2504-f51d-4ff4-840e-45f229fbbca9/dbsnp_132_b37.leftAligned.vcf.gz > /tmp/tmp90O2XU/dbsnp_132_b37.leftAligned.vcf.gz
gzip: /tmp/tmpjPJXyE/stge09f2504-f51d-4ff4-840e-45f229fbbca9/dbsnp_132_b37.leftAligned.vcf.gz: Too many levels of symbolic links
[job gzip.cwl] completed permanentFail
```

**Comment by kamichiotti** [comment]
Corrected issue by including "-c" to gzip command line.
